### ISSUE TITLE
rkhunter role should stat files it intends to include in lists

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/ansible-provision#1022]
We specify some paths for the rkhunter config, like this taken from defaults:

```yaml
  scriptwhitelist:
    - /bin/egrep
    - /bin/fgrep
    - /bin/which
    - /usr/bin/ldd
    # - /usr/bin/lwp-request
    - /usr/sbin/adduser
    # - /usr/sbin/prelink
    - /usr/sbin/unhide.rb
  allowhiddendir:
    - /etc/.java
  allowhiddenfile:
    - /etc/.etckeeper
  allowdevfile:
    - /dev/shm/network/ifstate
```

This currently needs to a list of actual paths, which is a bit of a pain - if not, `apt` hooks will fail and cause builds to stop. It would be ideal if this could be an *aspirational* list of file paths and the role stats each one on the server and only includes the ones that are actually there. That way a user can specify any old list of paths in the config and be confident that `ce-provision` will exclude from config any paths that are not present.
