### ISSUE TITLE
nodejs does not install node 18.x

### ISSUE THREAD

**Issue by matason** [codeenigma/ansible-provision#1762]
The nodejs role *should* install node 18.x and yarn stable by default however, at the time of writing, you end up with node v16.20.2 and yarn 1.22.19. These are the versions you get with the base image.

As per the [examples](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#examples), I tried:

```yml
- name: Ensure NodeJS and Yarn are installed.
  ansible.builtin.apt:
    pkg:
    - nodejs=v18.20.3
    - yarn=1.22.22
    state: present
```
and variants with and without the prefix v to no avail.

I found the only solution was to remove the packages first. When I do that, I get the following versions:

- node v18.17.1
- yarn 1.22.22
