### ISSUE TITLE
Better ASG healthcheck defaults

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/ansible-provision#863]
Defaults are currently this:

```yaml
  health_check_timeout: 5
  health_check_healthy_count: 5
  health_check_unhealthy_count: 2
  ```

I think we should reverse healthy and unhealthy, you want things to take longer to fail, but come good fast, not vice-versa.
