### ISSUE TITLE
Add a role for AWS OpenSearch

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/ansible-provision#923]
We have the following code in some client repos which could be enhanced and used to create a role here under `aws/aws_opensearch`:

```yaml
---
opensearch:
  engine_version: "OpenSearch_2.3"
  instance_type: "t3.medium.search"
  instance_count: 1
  zone_awareness: false
  dedicated_master: false
  availability_zone_count: 1
  warm_enabled: false
  cold_storage: false
  volume_type: "gp2"
  volume_size: 10
  subnets:
    - "subnet-XXXXXXXXXXXXXXXXX" # subnet ID
    - "sg-XXXXXXXXXXXXXX" # security group ID
  automated_snapshot_start_hour: 3
  auto_tune: false # not supported when t3's are used
  auto_tune_start: "2023-01-10"
  auto_tune_duration: 2
  auto_tune_cron: "cron(0 2 * * *)"
```

```yaml
---
- name: Create a service-linked role for OpenSearch.
  ansible.builtin.command:
    cmd: "aws iam create-service-linked-role --aws-service-name opensearchservice.amazonaws.com"
  ignore_errors: true # this will error after the first success
- name: Pause to allow for service-linked role propagation.
  ansible.builtin.pause:
    seconds: 30
- name: Create OpenSearch domain for dev environments.
  community.aws.opensearch:
    region: "{{ _aws_region }}"
    profile: "{{ _aws_profile }}"
    domain_name: "{{ _aws_resource_name }}"
    engine_version: "{{ opensearch.engine_version }}"
    cluster_config:
      instance_type: "{{ opensearch.instance_type }}"
      instance_count: "{{ opensearch.instance_count }}"
      zone_awareness: "{{ opensearch.zone_awareness }}"
      dedicated_master: "{{ opensearch.dedicated_master }}"
      availability_zone_count: "{{ opensearch.availability_zone_count }}"
      dedicated_master_instance_type: "{{ opensearch.dedicated_master_instance_type | default(omit) }}"
      dedicated_master_instance_count: "{{ opensearch.dedicated_master_instance_count | default(omit) }}"
      warm_enabled: "{{ opensearch.warm_enabled }}"
      warm_type: "{{ opensearch.warm_type | default(omit) }}"
      warm_count: "{{ opensearch.warm_count | default(omit) }}"
      cold_storage_options:
        enabled: "{{ opensearch.cold_storage }}" # boolean; true or false
    ebs_options:
      ebs_enabled: true
      volume_type: "{{ opensearch.volume_type }}"
      volume_size: "{{ opensearch.volume_size }}"
    access_policies: "{{ lookup('file', 'policy.json') | from_json }}"
    vpc_options:
      subnets: "{{ opensearch.subnets }}"
      security_groups: "{{ opensearch.security_groups }}"
    snapshot_options:
      automated_snapshot_start_hour: "{{ opensearch.automated_snapshot_start_hour }}"
    # auto_tune_options:
    #   enabled: "{{ opensearch.auto_tune }}" # boolean; true or false
    #   maintenance_schedules:
    #     - start_at: "{{ opensearch.auto_tune_start | default(omit) }}"
    #       duration:
    #         value: "{{ opensearch.auto_tune_duration | default(omit) }}"
    #         unit: "HOURS"
    #       cron_expression_for_recurrence: "{{ opensearch.auto_tune_cron | default(omit) }}"
    tags:
      Name: "{{ _aws_resource_name }}"
      Client: "{{ _infra_name }}"
      Infra: "{{ _infra_name }}"
      Env: "{{ _env_type }}"
    wait: true
```

This is clearly WIP stuff. We need to remove the `ignore_errors` and run some code to look up the service role first - if it exists we shouldn't try to create it again, and we can skip the pause too.

Similarly the tag handling can be better handled and we can sort out the `auto_tune` options.

Finally, I'm not sure if we can help this but the service tends to timeout waiting, so we can either set `wait: false` or see if there's a safer way to wait.
